name: govint
description: "Govint is all in one downloader app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  icons_launcher: ^2.1.7
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  grouped_list: ^6.0.0
  path_provider: ^2.1.3
  list_all_videos: ^1.2.0
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/images/bookmarks/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
